spring:
    application:
        name: config-service

    cloud:
        config:
            server:
                git:
                    uri: https://github.com/cjhlette/demo-config

server:
    port: 8888